In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import imageio
from sklearn.cluster import KMeans

In [4]:
#Read the image to be compressed
image = imageio.imread('https://storage.googleapis.com/kagglesdsdata/datasets/1148203/1925094/deep/Nature27.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=databundle-worker-v2%40kaggle-161607.iam.gserviceaccount.com%2F20211022%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20211022T155950Z&X-Goog-Expires=345599&X-Goog-SignedHeaders=host&X-Goog-Signature=631dcbdbc03b88e4c11e1b1a020c8761d4da6fd5f401aff56aa9f457cda1b0883160846e560edcb8ae42db604ba9d41c60b29b135cbee4a33b0fb3e590d09fcc9cc4a9649d5cb67474918842542ff80b3c1b0e8f805c5ffb0ba960e7416aa387c18689f480375df7f22b7d30470fadddacc2872beb8e4f32d4fbc2ceb78ebac1c9fe3e8801abd908b0084c199c0d4e7b3807835474effc00d4919f20a3e1584a9c87190411b1d46350f9b8a29b08ac37cf75850f4be755f9b54822df97155c895a0d07ffadc20ed1cc0df27e893d459d4524a079925c4e5dec286900ef4231fa9990df72f68384f69a5113bcf5f082d8cf0f7ee2f2516caef4390d2ca9f5994e')
image

Array([[[ 21,  20,  60],
        [ 20,  19,  59],
        [ 26,  25,  65],
        ...,
        [  0,  26, 107],
        [ 11,  38, 119],
        [  7,  34, 115]],

       [[ 19,  18,  58],
        [ 21,  20,  60],
        [ 26,  25,  65],
        ...,
        [ 10,  37, 118],
        [ 19,  46, 127],
        [ 11,  38, 119]],

       [[ 17,  16,  56],
        [ 24,  23,  63],
        [ 28,  27,  67],
        ...,
        [ 21,  46, 128],
        [ 22,  47, 129],
        [  5,  30, 112]],

       ...,

       [[111, 107,  98],
        [ 88,  84,  75],
        [125, 121, 112],
        ...,
        [ 54,  84, 112],
        [ 51,  80, 110],
        [ 42,  71, 101]],

       [[106, 102,  93],
        [ 90,  86,  77],
        [107, 103,  94],
        ...,
        [ 55,  86, 115],
        [ 63,  94, 123],
        [ 51,  82, 111]],

       [[120, 116, 107],
        [ 86,  82,  73],
        [ 94,  90,  81],
        ...,
        [ 61,  92, 121],
        [ 70, 101, 130],
        [ 44,  75, 106]]

In [5]:
rows = image.shape[0]
rows

1920

In [6]:
cols = image.shape[1]
cols

2160

In [7]:
#Reshape the image and flatten it
image = image.reshape(rows*cols, 3)
image

Array([[ 21,  20,  60],
       [ 20,  19,  59],
       [ 26,  25,  65],
       ...,
       [ 61,  92, 121],
       [ 70, 101, 130],
       [ 44,  75, 106]], dtype=uint8)

In [8]:
#Initialise the KMeans clustering object
#Increasing the n_clusters reduces the size of the image at the cost of reduced quality
kmeans = KMeans(n_clusters = 64)

In [9]:
#Train the model on the image
kmeans.fit(image)

KMeans(n_clusters=64)

In [10]:
#Assign every point to its assigned cluster
compressed_image = kmeans.cluster_centers_[kmeans.labels_]
compressed_image = np.clip(compressed_image.astype('uint8'), 0, 255)
compressed_image

array([[ 14,  20,  52],
       [ 14,  20,  52],
       [ 26,  30,  72],
       ...,
       [ 54,  84, 116],
       [ 73, 101, 131],
       [ 39,  65,  99]], dtype=uint8)

In [11]:
#Reshape the image to original size
compressed_image = compressed_image.reshape(rows, cols, 3)
compressed_image

array([[[ 14,  20,  52],
        [ 14,  20,  52],
        [ 26,  30,  72],
        ...,
        [ 18,  37, 113],
        [ 18,  37, 113],
        [ 18,  37, 113]],

       [[ 14,  20,  52],
        [ 14,  20,  52],
        [ 26,  30,  72],
        ...,
        [ 18,  37, 113],
        [ 30,  46, 123],
        [ 18,  37, 113]],

       [[ 14,  20,  52],
        [ 26,  30,  72],
        [ 26,  30,  72],
        ...,
        [ 30,  46, 123],
        [ 30,  46, 123],
        [ 18,  37, 113]],

       ...,

       [[118, 106, 106],
        [ 90,  75,  84],
        [130, 120, 114],
        ...,
        [ 54,  84, 116],
        [ 54,  84, 116],
        [ 39,  65,  99]],

       [[113,  97,  88],
        [ 90,  75,  84],
        [113,  97,  88],
        ...,
        [ 54,  84, 116],
        [ 54,  84, 116],
        [ 54,  84, 116]],

       [[118, 106, 106],
        [ 90,  75,  84],
        [104,  85,  73],
        ...,
        [ 54,  84, 116],
        [ 73, 101, 131],
        [ 39,  65,  99]]

In [12]:
#Write the compressed image to output
imageio.imsave('./compressed_image_64.jpg', compressed_image)