In [15]:
import imageio
import numpy as np
from sklearn.cluster import KMeans

In [16]:
#Read the image to be compressed
image = imageio.imread('image.jpg')
image

Array([[[  3, 155, 231],
        [  3, 156, 232],
        [  4, 157, 233],
        ...,
        [  3, 138, 228],
        [  4, 139, 229],
        [  4, 139, 229]],

       [[  3, 156, 232],
        [  4, 157, 233],
        [  5, 158, 234],
        ...,
        [  3, 138, 228],
        [  3, 138, 228],
        [  3, 138, 228]],

       [[  2, 158, 233],
        [  3, 159, 234],
        [  4, 160, 235],
        ...,
        [  3, 138, 228],
        [  2, 137, 227],
        [  2, 137, 227]],

       ...,

       [[127, 130,  53],
        [131, 136,  46],
        [141, 141,  51],
        ...,
        [ 19,  32,   0],
        [ 22,  29,  13],
        [ 31,  40,  11]],

       [[ 53,  57,   6],
        [117, 125,  48],
        [125, 131,  41],
        ...,
        [ 64,  85,  16],
        [ 39,  51,  15],
        [ 38,  48,  11]],

       [[122, 140,  58],
        [147, 165,  66],
        [111, 126,  33],
        ...,
        [ 35,  55,  20],
        [  9,  21,   7],
        [  5,  16,   2]]

In [17]:
rows = image.shape[0]
rows

432

In [18]:
cols = image.shape[1]
cols

1028

In [19]:
#Reshape the image and flatten it
image = image.reshape(rows*cols, 3)
image

Array([[  3, 155, 231],
       [  3, 156, 232],
       [  4, 157, 233],
       ...,
       [ 35,  55,  20],
       [  9,  21,   7],
       [  5,  16,   2]], dtype=uint8)

In [20]:
#Initialise the KMeans clustering object
#Increasing the n_clusters reduces the size of the image at the cost of reduced quality
kmeans = KMeans(n_clusters = 64)

In [21]:
#Train the model on the image
kmeans.fit(image)

KMeans(n_clusters=64)

In [22]:
#Assign every point to its assigned cluster
compressed_image = kmeans.cluster_centers_[kmeans.labels_]
compressed_image = np.clip(compressed_image.astype('uint8'), 0, 255)
compressed_image

array([[  2, 148, 228],
       [  3, 161, 231],
       [  3, 161, 231],
       ...,
       [ 46,  61,  25],
       [ 11,  27,   9],
       [  2,   9,   4]], dtype=uint8)

In [23]:
#Reshape the image to original size
compressed_image = compressed_image.reshape(rows, cols, 3)
compressed_image

array([[[  2, 148, 228],
        [  3, 161, 231],
        [  3, 161, 231],
        ...,
        [  2, 134, 225],
        [  2, 134, 225],
        [  2, 134, 225]],

       [[  3, 161, 231],
        [  3, 161, 231],
        [  3, 161, 231],
        ...,
        [  2, 134, 225],
        [  2, 134, 225],
        [  2, 134, 225]],

       [[  3, 161, 231],
        [  3, 161, 231],
        [  3, 161, 231],
        ...,
        [  2, 134, 225],
        [  2, 134, 225],
        [  2, 134, 225]],

       ...,

       [[126, 132,  42],
        [126, 132,  42],
        [142, 142,  60],
        ...,
        [ 11,  27,   9],
        [ 11,  27,   9],
        [ 25,  42,   5]],

       [[ 39,  57,   6],
        [126, 132,  42],
        [126, 132,  42],
        ...,
        [ 67,  86,   8],
        [ 39,  57,   6],
        [ 39,  57,   6]],

       [[126, 132,  42],
        [166, 162,  71],
        [108, 120,  36],
        ...,
        [ 46,  61,  25],
        [ 11,  27,   9],
        [  2,   9,   4]]

In [24]:
#Write the compressed image to output
imageio.imsave('compressed_image_64.jpg', compressed_image)